### ISSUE TITLE
add categories

### ISSUE THREAD

**Issue by onekk** [cobacdavid/dtv2#11]
Maybe it is a good idea to add some categories, maybe "kbdigits" and "kbsymbols" to group numbers and other symbols, on the keypad (for 104 keys keyboards).

'kbnlk' for could be put in another categories, maybe with "tab", "caps", "BACKS" and "ent" like in some keyboard color schemes group functional keys, leaving the alphabetic and number keys of one colors.

as example:
- white keys for letters and numbers, 
- a color functions keys, 
- another color for "modifiers" "shift, ctrl, caps lock, tab, backspace, widnows keys and fn, plus esc"
- another color for arrows and movement "arrows, pg up, pg dwn, home, end" (ins and del maybe another color?)

Regards

Carlo D.

**Comment by cobacdavid** [comment]
This is a very good idea. I just added `numpad` keys of your `it.json` to french and english json files.
So that now they appear in just one category : their respective rows.

The names `kbdigits` and `kbsymbols` are IMHO appropriate.
Could you add those categories in `dtv2.py` file (from line 94 to line 125 for categories definition) via a PR, please? or do you prefer I create them?

**Comment by onekk** [comment]
I think that it's better if you create them, and maybe i could make some little modifications after having see your implementation.

Regards

Carlo D.

**Comment by cobacdavid** [comment]
See https://github.com/cobacdavid/dtv2/commit/099d7e2379be5c0c90be9177ebf3ed2faf29e8aa
