### ISSUE TITLE
There is way to assign a brightness to the "static" or "kbd" key in **.dtv2change**  file?

### ISSUE THREAD

**Issue by onekk** [cobacdavid/dtv2#12]
Hello, I'm trying to assign a "brightness" to the keyboard:

```
{"kbd": "cyan"}
```

This will do the job of changing the color, and then:

```
dtv2change -r 
```

will do the job.

but If I want to assign a brightness there is way to do this in the **.dtv2change** file?

TIA and regards

Carlo D.

**Comment by cobacdavid** [comment]
Hi Carlo,
since last change this can be done using `hsl` tuple:
` $ dtv2change -kbd "hsl=(.5,1,.5)"`
gives you `cyan` (hue=180°, saturation=100% and luminosity=50%),  and
` $ dtv2change -kbd "hsl=(.5,1,.4)"`
will give you 80% of normal brightness and so on.

You can also increase to white (from 0.5 to 1).

Edit: One can find this in`colors` section of  `dtv2change` and `dtv2reader`  specific pages (her on github).
But I guess I should have mention this in the main doc. page...

**Comment by onekk** [comment]
Many thanks

Regards

Carlo D.
